version: 0.2

env:
  variables:
    JEKYLL_ENV: "production"

phases:
  install:
    commands:
      - gem install bundler
      - bundle install
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build
  post_build:
    commands:
      - echo "******** Uploading _site to S3://connorcg.com ********"
      - aws s3 sync _site/ s3://connorcg.com
