version: 0.2

env:
  variables:
    JEKYLL_ENV: "production"

phases:
  install:
    commands:
      - gem install bundler
      - bundle install
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build
  post_build:
    - echo "******** Uploading _site to S3://www.connorcg.com ********"
    - aws s3 sync _site/ s3://www.connorcg.com
