version: 0.2

phases:
  install:
    commands:
      - gem install jekyll jekyll-feed jekyll-seo-tag
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build
      - echo "******** Uploading to S3 ********"
      - aws s3 sync _site/ s3://www.connorcg.com
